spring.application.name=nosso-teto-api
spring.datasource.url=jdbc:mysql://localhost:3306/nossoteto_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
